---
- name: Include monitoring setup tasks
  ansible.builtin.include_tasks: setup.yml
  tags:
    - monitoring_setup

- name: Include monitoring deployment tasks
  ansible.builtin.include_tasks: deploy.yml
  tags:
    - monitoring_deploy
