---
app_name: devops-info-service
app_container_name: "{{ app_name }}"

docker_image: "{{ (dockerhub_username | default('your-dockerhub-username')) ~ '/' ~ app_name }}"
docker_image_tag: latest
app_registry_login_enabled: true
app_registry_url: https://index.docker.io/v1/
app_registry_reauthorize: false

app_port: 5000
app_container_port: 5000
app_restart_policy: unless-stopped
app_container_recreate: false
app_healthcheck_path: /health
app_healthcheck_status: 200
app_wait_timeout: 60
app_wait_delay: 2

app_env:
  HOST: "0.0.0.0"
  PORT: "{{ app_container_port | string }}"
  DEBUG: "false"

app_labels:
  app.kubernetes.io/name: "{{ app_name }}"
  app.kubernetes.io/managed-by: ansible

app_published_ports:
  - "{{ app_port }}:{{ app_container_port }}"
