apiVersion: v2
name: devops-info-python
description: Helm chart for the Python DevOps Info Service from Lab 9
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - python
  - flask
  - devops
  - helm
sources:
  - https://github.com/pepegx/DevOps-Core-Course
dependencies:
  - name: common-lib
    version: 0.1.0
    repository: file://../common-lib

