replicaCount: 1

app:
  environment: prod

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  nodePort: null
  clearNodePort: true

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
