apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "common.name" . }}
          image: "{{ required "Set .Values.image.repository or use k8s/devops-info-go/values-kind.yaml for local kind installs." .Values.image.repository }}:{{ required "Set .Values.image.tag or use k8s/devops-info-go/values-kind.yaml for local kind installs." .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: HOST
              value: {{ .Values.config.host | quote }}
            - name: PORT
              value: {{ .Values.config.port | quote }}
            - name: DEBUG
              value: {{ .Values.config.debug | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- include "common.httpProbe" .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- include "common.httpProbe" .Values.readinessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
