{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info-python.secretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  username: {{ .Values.secret.username | quote }}
  password: {{ .Values.secret.password | quote }}
{{- end }}
