apiVersion: v1
kind: Service
metadata:
  name: devops-info-go
  labels:
    app.kubernetes.io/name: devops-info-go
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: lab09
spec:
  selector:
    app.kubernetes.io/name: devops-info-go
  ports:
    - name: http
      port: 80
      targetPort: http
