apiVersion: v1
kind: Service
metadata:
  name: devops-info-python
  labels:
    app.kubernetes.io/name: devops-info-python
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: lab09
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: devops-info-python
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
